translate-messages: 'en_US'
teleport-to-spawn-on:
  first-join: true
  join: true
  respawn: true
  void-fall: true
teleport-delay-in-seconds: 3
check-version:
  enabled: true
disable-spawn-command-in-pvp:
  enabled: true
options:
  set-gamemode-on-join:
    enabled: true
    gamemode: 0
  set-fly-on-join:
    enabled: false
  set-max-health-on-join: false
  set-max-food-level-on-join: false
  disable-fall-damage: true
spawn-command:
  message-enabled: true
  need-permission: false
broadcast:
  player-join:
    enabled: true
  player-quit:
    enabled: true
  first-join:
    enabled: true
welcome-message:
  player-join:
    enabled: true
    text:
      - '&6Welcome, &7%nss_player_name%!'
      - '&6There are &7%nss_players_online% &6online!'
  first-join:
    enabled: true
    text:
      - '&6Welcome First Time, &7%nss_player_name%!'
      - '&6There are &7%nss_players_online% &6online!'
config-version: '1.4'
